### ISSUE TITLE
Update JSON Schema

### ISSUE THREAD

**Issue by tschmidtb51** [santosomar/csaf-json-visualizer#2]
@santosomar The current version of json.csaf.io still runs with an old version of the schema. Could you please update that to use: https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.0/json_schema/csaf_json_schema.json or https://docs.oasis-open.org/csaf/csaf/v2.0/csaf_json_schema.json

**Comment by dkruszew** [comment]
Current Schema:

![image](https://user-images.githubusercontent.com/54693931/165115660-350bd57f-4cd3-4cfc-a1bc-c50088ef6cee.png)

What is shown in json.csaf.io:

![image](https://user-images.githubusercontent.com/54693931/165115756-d54163cb-84c6-4914-8c66-2c00d1e4cd70.png)

Current Schema:

![image](https://user-images.githubusercontent.com/54693931/165116103-2bc62e08-a6f7-48bc-bea2-453a383294ed.png)

What is shown in json.csaf.io:

![image](https://user-images.githubusercontent.com/54693931/165116161-79cdf0c6-4f3f-445f-b8ef-da7e66cec8d3.png)

**Comment by santosomar** [comment]
Thank you! I just edited the html file with https://github.com/santosomar/csaf-json-visualizer/commit/0f501d6995fdbd7f7643d156b6dd77583961464a

I have to find a better way to automatically load this into the "tool".

Please check https://json.csaf.io

**Comment by tschmidtb51** [comment]
> I have to find a better way to automatically load this into the "tool".

Maybe use `editor.session.setValue(text)` in https://github.com/santosomar/csaf-json-visualizer/blob/master/js/app.js#L25-L32 instead? If the `text` is loaded from https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.0/json_schema/csaf_json_schema.json that should work... (Something similar to https://github.com/santosomar/csaf-json-visualizer/blob/0f501d6995fdbd7f7643d156b6dd77583961464a/js/jsv.js#L568)

**Note:** I haven't tested that yet. It might be problematic as I don't know when the function `setupEditor()` is called...

**Comment by tschmidtb51** [comment]
> Please check https://json.csaf.io

Looks like the run is queued but not done yet: https://github.com/santosomar/csaf-json-visualizer/actions/runs/2221129845

**Comment by santosomar** [comment]
> > Please check https://json.csaf.io
> 
> Looks like the run is queued but not done yet: https://github.com/santosomar/csaf-json-visualizer/actions/runs/2221129845

Should be done now...
https://github.com/santosomar/csaf-json-visualizer/actions/runs/2221129845

**Comment by tschmidtb51** [comment]
> > > Please check https://json.csaf.io
> > 
> > 
> > Looks like the run is queued but not done yet: https://github.com/santosomar/csaf-json-visualizer/actions/runs/2221129845
> 
> Should be done now... https://github.com/santosomar/csaf-json-visualizer/actions/runs/2221129845

Yes. Works for me - Thank you! I submitted a small PR (#3) to remove leftover white space...
